// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AIIntegration","status":true,"description":"Integrates AI (e.g., OpenAI GPT) for dynamic dialogues and interactions.","parameters":{}}
];
